import { PageHero } from "../components/PageHero";
import { SectionHeading } from "../components/SectionHeading";
import { SiteFooter } from "../components/SiteFooter";
import { SiteHeader } from "../components/SiteHeader";
import { approachSteps, consultationOutcomes, deliverables, freeConsultationSteps, ongoingSupportExamples, problemStates } from "../../content/site";

export default function ServicesPage() { return <><SiteHeader /><main><PageHero eyebrow="SERVICES" title="困り方から、技術判断と実行へ" lead="サービス名を選ぶ必要はありません。今の困り方から、まず何を確かめ、どこまで支援が必要かを一緒に整理します。" />
  <section id="before-after" className="section"><div className="container"><SectionHeading eyebrow="FROM CONFUSION TO NEXT STEP" title="困り方別 Before / After" text="相談前の混乱を、次の判断や行動へ進める状態に変えます。" /><div className="outcome-grid">{consultationOutcomes.map((item, index) => <article key={item.before}><span>{String(index + 1).padStart(2, "0")}</span><div><p className="outcome-before">{item.before}</p><p className="outcome-arrow" aria-hidden="true">↓</p><p className="outcome-after">{item.after}</p></div></article>)}</div></div></section>
  <section id="consultation-issues" className="section section-muted"><div className="container"><SectionHeading eyebrow="WHAT WE SOLVE" title="相談できる課題" text="問題が一つの技術分野に収まらず、何から手をつければよいか分からない状況を扱います。" /><div className="problem-grid light-problem-grid">{problemStates.map((item, index) => <article className="problem-card" key={item.title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>
  <section id="support-process" className="section"><div className="container"><SectionHeading eyebrow="HOW WE WORK" title="支援の進め方" text="技術の根拠を確認しながら、判断と実行をつなぎます。" /><ol className="approach-list">{approachSteps.map((step, index) => <li key={step.title}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{step.title}</h3><p>{step.text}</p></div></li>)}</ol></div></section>
  <section id="deliverables" className="section section-muted"><div className="container"><SectionHeading eyebrow="DELIVERABLES" title="得られる成果物" text="相談や案件の内容に応じて、判断と次の行動に使えるものを残します。" /><ul className="deliverables-grid">{deliverables.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span>{item}</li>)}</ul></div></section>
  <section className="section"><div className="container"><SectionHeading eyebrow="ONGOING SUPPORT" title="継続支援の例" text="30分で終わる相談もあります。追加の調査や実装が必要なときだけ、必要な範囲をご提案します。" /><div className="ongoing-support-grid">{ongoingSupportExamples.map((item, index) => <article key={item.title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div></section>
  <section className="section section-ink consultation-section compact-consultation" aria-labelledby="services-consultation-title"><div className="container consultation-layout"><div><p className="eyebrow">FREE 30-MINUTE CONSULTATION</p><h2 id="services-consultation-title">30分で、次に何をすべきかを整理します</h2><p>案件化を前提にしません。30分で十分ならそこで終了し、追加支援が必要な場合のみ次の進め方をご提案します。</p><a className="button button-outline-light" href="/contact">30分無料で相談する <span aria-hidden="true">→</span></a></div><ol className="consultation-flow" aria-label="無料相談の流れ">{freeConsultationSteps.map((step, index) => <li key={step}><span>{String(index + 1).padStart(2, "0")}</span>{step}</li>)}</ol></div></section>
</main><SiteFooter /></> }
