import { SectionHeading } from "./components/SectionHeading";
import { SiteFooter } from "./components/SiteFooter";
import { SiteHeader } from "./components/SiteHeader";
import Link from "next/link";
import { approachSteps, consultationJourney, consultationMemo, deliverables, insightCategories, researchProjects } from "../content/site";

export default function Home() {
  return <><SiteHeader /><main>
    <section className="hero hero-decision" aria-labelledby="hero-title"><div className="hero-inner hero-layout">
      <div className="hero-message"><p className="eyebrow hero-eyebrow">TECHNICAL CONSULTATION</p><h1 id="hero-title">どこに頼めばいいか分からない。<br /><em>そんな技術課題を、<br />構造から解く。</em></h1><p className="hero-copy">前例や専門家が見つからず、技術・業務・組織の制約が絡み合う課題を、全体構造から捉え直します。技術判断から検証・設計・実装まで支援します。</p><div className="hero-actions"><Link className="button button-primary" href="/contact">30分無料で相談する <span aria-hidden="true">→</span></Link></div><div className="hero-journey" aria-label="構想から実行まで、相談で扱う4つの段階"><p className="hero-journey-title">構想から実行までの4つの段階</p>{consultationJourney.map((item) => <article key={item.id}><span className="hero-journey-number">{item.id}</span><div className="hero-journey-before"><p className="hero-journey-kind">Before</p><p>{item.before}</p></div><span className="hero-journey-arrow" aria-hidden="true">→</span><div className="hero-journey-after"><p className="hero-journey-kind">After</p><p>{item.after}</p></div></article>)}</div></div>
    </div></section>

    <section id="before-after" className="section" aria-labelledby="before-after-title"><div className="container"><SectionHeading eyebrow="DETAILS BY STAGE" title="各段階で起こる、具体的な困りごと" text="4つの段階それぞれで、判断や実行を止めていることを具体的に確認します。独立したサービスを選ぶのではなく、今いる段階から次の一手を決めます。" /><div className="journey-detail-list">{consultationJourney.map((item) => <article key={item.id}><header><span>{item.id}</span><div><p>{item.phase}</p><h3>{item.before}</h3></div></header><ul>{item.examples.map((example) => <li key={example.issue}><p>{example.issue}</p><span>{example.support}</span></li>)}</ul></article>)}</div></div></section>

    <section id="free-consultation" className="consultation-memo-section" aria-labelledby="consultation-title"><div className="container"><div className="consultation-memo-heading"><p className="eyebrow">FREE 30-MINUTE CONSULTATION</p><h2 id="consultation-title">まずは30分、その場で解決しにいきます</h2><p>初回30分は無料です。課題が整理されていなくても、技術名が分からなくてもご相談いただけます。案件化を目的に引き延ばすことはせず、その場で解決できることはその場で整理・回答します。</p></div><div className="consultation-memo-preparation"><div><h3>相談に必要な情報</h3><p>資料の準備は不要です。分かる範囲だけお聞かせください。</p></div><ol className="consultation-memo-grid" aria-label="相談時に共有いただきたいこと">{consultationMemo.map((item, index) => <li key={item.title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{item.title}</h3><p>{item.text}</p><small>{item.example}</small></li>)}</ol></div><div className="consultation-memo-closure"><div><p className="eyebrow">AFTER 30 MINUTES</p><h3>30分で十分なら、そこで終了します</h3></div><p>その場で解決できることはその場で回答します。追加の調査・検証・設計・実装が必要な場合にだけ、次の支援をご提案します。</p></div><div className="consultation-memo-cta"><Link className="button button-primary" href="/contact">30分無料で相談する <span aria-hidden="true">→</span></Link></div></div></section>

    <section id="support-process" className="section" aria-labelledby="process-title"><div className="container"><SectionHeading eyebrow="HOW WE WORK" title="支援の進め方" text="調査だけ、実装だけに分けず、判断に必要な工程をつなげます。必要なところまでを、必要な深さで進めます。" /><ol className="approach-list">{approachSteps.map((step, index) => <li key={step.title}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{step.title}</h3><p>{step.text}</p></div></li>)}</ol></div></section>

    <section id="deliverables" className="section" aria-labelledby="deliverables-title"><div className="container"><SectionHeading eyebrow="DELIVERABLES" title="判断と実行に残る成果物" text="案件の内容に応じて、関係者が次の判断や実装へ使える形に整理してお渡しします。" /><ul className="deliverables-grid">{deliverables.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span>{item}</li>)}</ul></div></section>

    <section className="section" aria-labelledby="insights-title"><div className="container"><div className="section-heading-row"><SectionHeading eyebrow="INSIGHTS" title="この会社が、どう考えるか" text="特殊IT技研が、技術課題をどう読み、どう判断しているかを公開しています。" /><Link className="text-link" href="/insights">Insightsを見る →</Link></div><div className="insight-category-grid insight-category-grid-four">{insightCategories.slice(0, 4).map((category) => <article id={category.id} key={category.title}><h3>{category.title}</h3><p>{category.description}</p><ul>{category.examples.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div></div></section>

    <section className="section" aria-labelledby="products-title"><div className="container"><div className="section-heading-row"><SectionHeading eyebrow="PRODUCTS / R&D" title="自社プロダクト・研究開発" text="以下は受託案件ではなく、特殊IT技研が自ら開発・提供するプロダクト群です。" /><Link className="text-link" href="/products">Productsを見る →</Link></div><div className="research-list">{researchProjects.map((project) => <article id={project.id} key={project.title}><p>{project.level}</p><h3>{project.title}</h3><div><p>{project.description}</p><small>{project.status}</small></div></article>)}</div></div></section>

    <section className="section final-cta-section" aria-labelledby="final-cta-title"><div className="container final-cta"><div><p className="eyebrow">CONTACT</p><h2 id="final-cta-title">相談先が分からない段階で構いません</h2><p>課題が整理されていなくても、技術名称が分からなくても相談可能です。まず30分で、何を考えるべきかを整理します。</p></div><Link className="button button-primary" href="/contact">30分無料で相談する <span aria-hidden="true">→</span></Link></div></section>
  </main><SiteFooter /></>;
}
