import { SectionHeading } from "./components/SectionHeading";
import { SiteFooter } from "./components/SiteFooter";
import { SiteHeader } from "./components/SiteHeader";
import { approachSteps, consultationMemo, consultationOutcomes, deliverables, insightCategories, researchProjects } from "../content/site";

export default function Home() {
  return <><SiteHeader /><main>
    <section className="hero" aria-labelledby="hero-title"><div className="hero-grid" aria-hidden="true" /><div className="hero-inner hero-layout">
      <div className="hero-message"><p className="eyebrow hero-eyebrow">TECHNICAL CONSULTATION</p><h1 id="hero-title">どこに頼めばいいか分からない。<br /><em>そんな技術課題を、<br />構造から解く。</em></h1><p className="hero-copy">前例や専門家が見つからず、技術・業務・組織の制約が絡み合う課題を、全体構造から捉え直します。技術判断から検証・設計・実装まで支援します。</p><div className="hero-actions"><a className="button button-primary" href="/contact">30分無料で相談する <span aria-hidden="true">→</span></a><a className="button button-quiet" href="#before-after">相談できる課題を見る <span aria-hidden="true">↓</span></a></div><p className="hero-capabilities"><span>資料の準備は不要</span><span>技術名が分からなくても可</span><span>案件化は前提にしません</span></p></div>
      <aside className="hero-flow" aria-label="特殊IT技研による課題整理から次の一手までの流れ"><div className="flow-stage flow-start"><p>ご相談前</p><ul><li>何の専門家に頼めばよいか分からない</li><li>技術・業務・運用・組織の論点が絡んでいる</li><li>ベンダーの説明を評価できない</li><li>次に何を確認すべきか分からない</li></ul></div><div className="flow-action"><span aria-hidden="true">↓</span><strong>一緒に状況を整理</strong><small>お話と既存資料から、論点と制約を確かめます。</small></div><div className="flow-stage flow-outcome"><p>相談後</p><ul><li>本当の論点が分かる</li><li>できること・できないことが分かる</li><li>必要な検証が分かる</li><li>設計・実装・判断の次の一手が分かる</li></ul><div className="flow-output"><span>判断</span><span>検証</span><span>設計</span><span>実装</span></div></div></aside>
    </div></section>

    <section id="before-after" className="section" aria-labelledby="before-after-title"><div className="container"><SectionHeading eyebrow="FROM CONFUSION TO NEXT STEP" title="困り方から、次の一手へ" text="サービス名を選ぶ必要はありません。今の困り方から、最初に何を確認し、どう進めるべきかを整理します。" /><div className="outcome-grid">{consultationOutcomes.map((item, index) => <article key={item.before}><span>{String(index + 1).padStart(2, "0")}</span><div><p className="outcome-before">{item.before}</p><p className="outcome-arrow" aria-hidden="true">↓</p><p className="outcome-after">{item.after}</p></div></article>)}</div></div></section>

    <section className="section section-ink consultation-memo-section" aria-labelledby="consultation-title"><div className="container"><div className="consultation-memo-heading"><p className="eyebrow">FREE 30-MINUTE CONSULTATION</p><h2 id="consultation-title">相談の準備は、3つだけ</h2><p>このうち一つでも分かれば、相談を始められます。資料をそろえたり、依頼内容を決めたりする必要はありません。</p></div><ol className="consultation-memo-grid" aria-label="相談時に共有いただきたいこと">{consultationMemo.map((item, index) => <li key={item.title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{item.title}</h3><p>{item.text}</p><small>{item.example}</small></li>)}</ol><div className="consultation-memo-cta"><p>案件化は前提にしません。30分で足りれば、その場で終了します</p><a className="button button-outline-light" href="/contact">30分無料で相談する <span aria-hidden="true">→</span></a></div></div></section>

    <section id="support-process" className="section section-muted" aria-labelledby="process-title"><div className="container"><SectionHeading eyebrow="HOW WE WORK" title="支援の進め方" text="調査だけ、実装だけに分けず、判断に必要な工程をつなげます。必要なところまでを、必要な深さで進めます。" /><ol className="approach-list">{approachSteps.map((step, index) => <li key={step.title}><span>{String(index + 1).padStart(2, "0")}</span><div><h3>{step.title}</h3><p>{step.text}</p></div></li>)}</ol></div></section>

    <section id="deliverables" className="section" aria-labelledby="deliverables-title"><div className="container"><SectionHeading eyebrow="DELIVERABLES" title="判断と実行に残る成果物" text="案件の内容に応じて、関係者が次の判断や実装へ使える形に整理してお渡しします。" /><ul className="deliverables-grid">{deliverables.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span>{item}</li>)}</ul></div></section>

    <section className="section section-muted" aria-labelledby="insights-title"><div className="container"><div className="section-heading-row"><SectionHeading eyebrow="INSIGHTS" title="この会社が、どう考えるか" text="特殊IT技研が、技術課題をどう読み、どう判断しているかを公開しています。" /><a className="text-link" href="/insights">Insightsを見る →</a></div><div className="insight-category-grid insight-category-grid-four">{insightCategories.slice(0, 4).map((category) => <article id={category.id} key={category.title}><h3>{category.title}</h3><p>{category.description}</p><ul>{category.examples.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div></div></section>

    <section className="section" aria-labelledby="products-title"><div className="container"><div className="section-heading-row"><SectionHeading eyebrow="PRODUCTS / R&D" title="自社プロダクト・研究開発" text="以下は受託案件ではなく、特殊IT技研が自ら開発・提供するプロダクト群です。" /><a className="text-link" href="/products">Productsを見る →</a></div><div className="research-list">{researchProjects.map((project) => <article id={project.id} key={project.title}><p>{project.level}</p><h3>{project.title}</h3><div><p>{project.description}</p><small>{project.status}</small></div></article>)}</div></div></section>

    <section className="section final-cta-section" aria-labelledby="final-cta-title"><div className="container final-cta"><div><p className="eyebrow">CONTACT</p><h2 id="final-cta-title">相談先が分からない段階で構いません</h2><p>課題が整理されていなくても、技術名称が分からなくても相談可能です。まず30分で、何を考えるべきかを整理します。</p></div><a className="button button-primary" href="/contact">30分無料で相談する <span aria-hidden="true">→</span></a></div></section>
  </main><SiteFooter /></>;
}
